server:  port: 8001
spring:
  application:
    name: car-service
  config:    import: optional:configserver:http://localhost:8888
  datasource:    url: jdbc:postgresql://cpds-devops.cpdi.sinse.lan:5434/carservicedb
    username: postgres    password: Sinse.2018
  jpa:
    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:      ddl-auto: updateeureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka